const express = require('express')
const app = express()
const cors = require('cors')
app.use(cors())
const subcategoriesRoutes = require('./routes/subcategories');
const variantRoutes = require('./routes/variants')
const userRoutes = require('./routes/users')
const productRoutes = require('./routes/products')
const categoryRoutes = require('./routes/categories')
const cartRoutes = require('./routes/carts')
const orderRoutes = require('./routes/Orders')
const reviewRoutes = require('./routes/reviews')
const cartItemRoutes = require('./routes/cart_items')
const orderItemRoutes = require('./routes/orderitems')
const authRoutes = require('./routes/auth')
const saleRoutes = require('./routes/sales')
const errorMiddleware = require('./middlewares/error.middleware')
const path = require('path')
const productImageRoutes = require('./routes/productImages')
const addressRoutes = require('./routes/addresses')
const paymentRoutes = require('./routes/payments')


app.use('/uploads', express.static(path.resolve(__dirname, '../uploads')))
app.use('/product-images', productImageRoutes)
app.use('/sales', saleRoutes)
app.use('/order-items', orderItemRoutes)
app.use(express.json())
app.use('/reviews', reviewRoutes)
app.use('/auth', authRoutes)
app.use('/users', userRoutes)
app.use('/products', productRoutes)
app.use('/categories', categoryRoutes)
app.use('/carts', cartRoutes)
app.use('/orders', orderRoutes)
app.use('/variants', variantRoutes)
app.use('/cart-items', cartItemRoutes)
app.use('/addresses', addressRoutes)
app.use('/payments', paymentRoutes)
app.use('/subcategories', subcategoriesRoutes);
app.use(errorMiddleware)
const swaggerUi = require('swagger-ui-express')
const swaggerSpec = require('./config/swagger')


module.exports = app