const t = {
  fontDisplay: "'Cormorant Garamond', 'Georgia', serif",
  fontBody: "'Jost', 'Helvetica Neue', Arial, sans-serif",
  bg: '#F6F4F1', surface: '#FFFFFF', border: '#DDD9D3',
  text: '#141412', muted: '#6E6B66', accent: '#141412',
  danger: '#7B1D1D', dangerBg: '#FAF0EF',
  success: '#1A4A2E', successBg: '#F0F7F2',
  shadowMd: '0 4px 24px rgba(20,20,18,0.09)',
}

const styles = {
  page: {
    minHeight: '100vh',
    backgroundColor: t.bg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: t.fontBody,
    padding: '60px 20px',
  },
  card: {
    backgroundColor: t.surface,
    padding: '56px 48px',
    width: '100%',
    maxWidth: '460px',
    boxShadow: t.shadowMd,
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
  },
  title: {
    fontFamily: t.fontDisplay,
    fontSize: '36px',
    fontWeight: '400',
    color: t.text,
    letterSpacing: '0.04em',
    marginBottom: '32px',
    textAlign: 'center',
  },
  input: {
    fontFamily: t.fontBody,
    fontSize: '13px',
    color: t.text,
    backgroundColor: 'transparent',
    border: 'none',
    borderBottom: `1px solid ${t.border}`,
    padding: '10px 0',
    outline: 'none',
    letterSpacing: '0.02em',
    width: '100%',
    marginBottom: '16px',
    display: 'block',
  },
  dateField: {
    display: 'block',
    marginBottom: '16px',
    position: 'relative',
    width: '100%',
  },
  datePlaceholder: {
    color: t.muted,
    fontFamily: t.fontBody,
    fontSize: '13px',
    left: 0,
    letterSpacing: '0.02em',
    pointerEvents: 'none',
    position: 'absolute',
    top: '10px',
    zIndex: 1,
  },
  dateInput: {
    marginBottom: 0,
    position: 'relative',
  },
  emptyDateInput: {
    color: 'transparent',
  },
  button: {
    fontFamily: t.fontBody,
    fontSize: '12px',
    fontWeight: '500',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#FFFFFF',
    backgroundColor: t.accent,
    border: 'none',
    padding: '14px 0',
    cursor: 'pointer',
    marginTop: '12px',
    width: '100%',
  },
  error: {
    fontFamily: t.fontBody,
    fontSize: '12px',
    color: t.danger,
    backgroundColor: t.dangerBg,
    border: `1px solid ${t.danger}20`,
    padding: '10px 14px',
    marginBottom: '16px',
    letterSpacing: '0.02em',
  },
  success: {
    fontFamily: t.fontBody,
    fontSize: '12px',
    color: t.success,
    backgroundColor: t.successBg,
    border: `1px solid ${t.success}20`,
    padding: '10px 14px',
    marginBottom: '16px',
    letterSpacing: '0.02em',
  },
  loginRedirect: {
    fontFamily: t.fontBody,
    fontSize: '12px',
    color: t.muted,
    textAlign: 'center',
    marginTop: '20px',
    letterSpacing: '0.02em',
  },
  loginLink: {
    color: t.text,
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
  },
}

export default styles
